name       : python-backports.entry_points_selectable
version    : 1.1.0
release    : 1
source     :
    - https://github.com/jaraco/backports.entry_points_selectable/archive/refs/tags/v1.1.0.tar.gz : cc33223f3b5c1b920d3d0b9de45e1d7483592ffcd6f9cf155d1b316f03d7a376
license    : MIT
component  : programming.python
summary    : Compatibility shim to ease adoption of importlib_metadata 3.6
description: |
    Compatibility shim to ease adoption of importlib_metadata 3.6. Supplies forward-compatibility of "selectable" entry points even on older versions of importlib_metadata and importlib.metadata, and avoids usage that triggers deprecation warnings.
builddeps  :
    - python-pytest # check
    - python-setuptools-scm
    - python-wheel
setup      : |
    sed -i '5 i\Version: %version%' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
