name       : python-backports.entry_points_selectable
version    : 1.2.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/b/backports.entry_points_selectable/backports.entry_points_selectable-1.2.0.tar.gz : 4706f59179657ca7c1d325a543ee1370f8f46331f432bcac62fab242fdf0afa5
homepage   : https://github.com/jaraco/backports.entry_points_selectable
license    : MIT
component  : programming.python
summary    : Compatibility shim to ease adoption of importlib_metadata 3.6
description: |
    Compatibility shim to ease adoption of importlib_metadata 3.6. Supplies forward-compatibility of "selectable" entry points even on older versions of importlib_metadata and importlib.metadata, and avoids usage that triggers deprecation warnings.
builddeps  :
    - python-build
    - python-installer
    - python-pytest # check
    - python-setuptools-scm
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
